### ISSUE TITLE
AzureFile as a Volume can not work

### ISSUE THREAD

**Issue by ryutamaki** [grafana/grafana-docker#118]
Hi, I need some help because I'm stacked to deploy grafana as a container into kubernetes.

I'm using AzureFile as a volume and get error like this.
It says, I dont have permissions to mounted volume but I couldn't find any way to change permissions while initializing container.

Does anyone knows how to treat this problem?

```
t=2017-12-28T04:06:57+0000 lvl=info msg="Starting Grafana" logger=server version=4.6.3 commit=7a06a47 compiled=2017-12-14T08:36:59+0000
t=2017-12-28T04:06:57+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2017-12-28T04:06:57+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2017-12-28T04:06:57+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2017-12-28T04:06:57+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2017-12-28T04:06:57+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2017-12-28T04:06:57+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
t=2017-12-28T04:06:57+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_PASSWORD=*********"
t=2017-12-28T04:06:57+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2017-12-28T04:06:57+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2017-12-28T04:06:57+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2017-12-28T04:06:57+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2017-12-28T04:06:57+0000 lvl=info msg="App mode production" logger=settings
t=2017-12-28T04:06:57+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-12-28T04:06:57+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2017-12-28T04:06:57+0000 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: unable to open database file\n"
```

Here is my yaml file for kubernetes deployment

```yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: 'grafana/grafana:latest'
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-volume
              mountPath: /var
      volumes:
        - name: grafana-volume
          azureFile:
            secretName: azure-file-secret
            shareName: grafana
            readOnly: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
```

thanks

**Comment by xlson** [comment]
Hi @ryutamaki,

Sorry for not responding previously. Were you able to solve your issue?

I presume you have moved on but will at least describe what Grafana expects the permissions to be at this time:
In current (<5.1) Grafana versions the docker image expects to boot as root and switch to the grafana user (uid = 104, gid=107). When we release 5.1 we will support running Grafana with any user id. I'm afraid I don't know Azure and Kubernetes well enough to be of any help in solving how to make sure that the volume is created with the right permissions.

**Comment by omgsarge** [comment]
I too get this, I believe the user the container ends up running as does not have permission to write to the Azure-File storage claim, even though the volume mounts correctly.

**Comment by xlson** [comment]
@omgsarge could you try doing this with the latest build from master? `grafana/grafana:master`. It probably won't help but might be worth trying as file permissions are handled differently than in the old container. Otherwise you probably want to find a way to specify what user/group the volume is created for. For the new container it should be 472.

**Comment by alexvicegrab** [comment]
@xlon, would be great to be able to set the grafana uid to something else, so I can use a single Azure storage class to handle multiple applications, but as such, I've been solving this same issue by creating a storage class like this:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile0grafana
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: ${AZURE_STORAGE_ACCOUNT}
mountOptions:
  - dir_mode=0750
  - file_mode=0750
  - uid=104
  - gid=107
```

This has gotten me further, but am seeing another issue:

```
t=2018-04-30T16:51:03+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2018-04-30T16:51:03+0000 lvl=info msg="Executing migration" logger=migrator id="create migration_log table"
t=2018-04-30T16:51:08+0000 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: database is locked\n
```
