### ISSUE TITLE
Internal host names are not resolved

### ISSUE THREAD

**Issue by simonszu** [grafana/grafana-docker#144]
Hi,

i have all my docker containers in the same backend network. I want to deploy Grafana with MariaDB for storage, so i have created a container `grafana_db_1`, and also `grafana_app_1` for Grafana itself (they were created by docker compose). 
However, Grafana isn't starting, since it cannot find the database container. The log file says:
```
EROR[03-23|06:50:55] Fail to initialize orm engine            logger=sqlstore error="Sqlstore::Migration failed err: dial tcp: lookup grafana_db_1 on 8.8.8.8:53: no such host\n"
```
Although it is quite obvious that Google DNS cannot find another container on the internal network, i have no idea why Grafana is querying Google DNS and not the DNS of the docker network. Shouldn't Grafana query the network DNS to find any other internal container names?

**Comment by xlson** [comment]
Hi,

Yes, Grafana should query the internal dns representation first. My guess would be that the grafana container is unable to lookup your db container locally and then tries to access the external dns and fails again, but this time because it can't reach the external dns.

It would be helpful to see a `docker-compose.yml` file that reproduces your issue. I'm guessing it's either something with your compose configuration or your Docker setup.

**Comment by simonszu** [comment]
OK. This is the docker-compose setup. It is slightly different from pure docker compose syntax, since i deploy the containers with ansible, but it should generally be understandable. 
```
- name: Start grafana docker service
  docker_service:
    pull: yes
    project_name: grafana
    definition:
      version: '2'
      services:
        app:
          restart: unless-stopped
          image: grafana/grafana
          ports:
          - "3000:3000"
          volumes:
          - "{{ docker_datadir }}/grafana/app:/var/lib/grafana"
          environment:
            GF_SERVER_ROOT_URL: https://mydomain.tld
            GF_DATABASE_TYPE: mysql
            GF_DATABASE_HOST: grafana_db_1
            GF_DATABASE_NAME: grafana
            GF_DATABASE_USER: grafana
            GF_DATABASE_PASSWORD: XXXX
        db:
          restart: unless-stopped
          image: mariadb
          environment:
            MYSQL_ROOT_PASSWORD: XXXX
            MYSQL_USER: grafana
            MYSQL_PASSWORD: XXXX
            MYSQL_DATABASE: grafana
          volumes:
          - "{{ docker_datadir }}/grafana/db:/var/lib/mysql"
          networks:
          - default
      networks:
        default:
          external:
            name: backend
```

This is the definition of the docker network:
```
- name: Create network for backend connection
  docker_network:
    name: backend
    driver_options:
      com.docker.network.bridge.name: dck-backend
    ipam_options:
      subnet: 172.19.1.0/24
      gateway: 172.19.1.1
```
But i doubt that there's a problem with the network setup or the docker compose in general, since i use this network and the same structure of the docker compose file to deploy other apps on the same host, which, e.g. Matomo, are an app container and a MariaDB database container as well.
