### ISSUE TITLE
v5.1.0 fails with aws credentials injected via environment variables

### ISSUE THREAD

**Issue by dhallam** [grafana/grafana-docker#158]
Hi,

The issue that is now closed at https://github.com/grafana/grafana-docker/issues/156 is still a genuine issue. Rolling back to 5.0.4 works perfectly, but 5.1.0 doesn't.

The body of the issue in https://github.com/grafana/grafana-docker/issues/156 is the same with the exception that the host that I am running on is running rancheros.

Best regards,

Dave

**Comment by dhallam** [comment]
Example using the following `docker-compose.yml`

```
version: "3"
services:
  grafana-5.0.4:
    image: grafana/grafana:5.0.4
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      GF_AWS_PROFILES: default
      GF_AWS_default_ACCESS_KEY_ID: ${GRAFANA_ACCESS_KEY_ID}
      GF_AWS_default_SECRET_ACCESS_KEY: ${GRAFANA_SECRET_ACCESS_KEY}
      GF_AWS_default_REGION: eu-west-2
  grafana-5.1.0:
    image: grafana/grafana:5.1.0
    restart: unless-stopped
    ports:
      - 3002:3000
    environment:
      GF_AWS_PROFILES: default
      GF_AWS_default_ACCESS_KEY_ID: ${GRAFANA_ACCESS_KEY_ID}
      GF_AWS_default_SECRET_ACCESS_KEY: ${GRAFANA_SECRET_ACCESS_KEY}
      GF_AWS_default_REGION: eu-west-2
```

Shelling into the 5.0.4 instance using `docker-compose exec grafana-5.0.4 bash`

That logs me in as the `root` user.
```
root@8650e969c728:/usr/share/grafana/.aws# ls -l
total 4
-rw------- 1 grafana grafana 135 May  9 10:34 credentials
```

And the process: 
```
root@8650e969c728:/usr/share/grafana/.aws# ps -ef | grep grafan[a]
grafana      1     0  0 10:34 ?        00:00:00 /usr/sbin/grafana-server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini cfg:default.log.mode=console cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins cfg:default.paths.provisioning=/etc/grafana/provisioning
```

Then shelling into the 5.1.0 container using `docker-compose exec grafana-5.1.0 bash`

That logs me in as the `grafana` user.

```
grafana@ecc3ad438c3e:/usr/share/grafana/.aws$ ls -l
total 4
-rw------- 1 grafana grafana 135 May  9 10:34 credentials
```

There's no `ps` in the container so didn't get process info.

When I go to the web interface, I can create a CloudWatch DataSource with `Credentials file` on the `5.0.4` instance, but not on the `5.1.0` instance - I just get a red box with a white warning triangle in it when I press `Save & Test`.

And in the logs:

```
grafana-5.1.0_1  | t=2018-05-09T10:46:24+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="Failed to call cloudwatch:ListMetrics, NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
grafana-5.1.0_1  | t=2018-05-09T10:46:24+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=172.23.0.1 time_ms=12003 size=34 referer=http://localhost:3002/datasources/edit/1?gettingstarted
```
