### ISSUE TITLE
GF_INSTALL_PLUGINS Not working

### ISSUE THREAD

**Issue by mjgorman** [grafana/grafana-docker#54]
Tried adding this as a an environment variable on my Grafana container with the example provided plugins "grafana-clock-panel,grafana-simple-json-datasource" and they are not installed. if i install them manually and restart the container they are there, but if the container gets upgrade/moved to a different host in the cluster the plugins are gone. I don't mind making plugins a persistent storage location if need be, but shouldn't the GF_INSTALL_PLUGINS env be working? 

Thanks

**Comment by DanCech** [comment]
can you provide an example of how to reproduce the problem you're seeing?

**Comment by mjgorman** [comment]
using docker compose:
```
grafana:
  ports:
  - 3000:3000/tcp
  environment:
    GF_DATABASE_TYPE: mysql
    GF_DATABASE_HOST: xxx
    GF_DATABASE_USER: xxx
    GF_DATABASE_PASSWORD: xxx
    GF_DATABASE_NAME: xxx
    GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
```
clock panel and simple json data source are not installed.
