### ISSUE TITLE
Plugin versions not working

### ISSUE THREAD

**Issue by Puneeth-n** [grafana/grafana-docker#76]
The plugin version seems to be broken again. #59 #60 

docker image 4.1.1

My docker-compose config:
```
grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
        - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,grafana-worldmap-panel,stagemonitor-elasticsearch-app,grafana-simple-json-datasource  1.2.3
        - GF_GRAFANA_NET=https://grafana.net
        - GF_LOG_MODE=console
        - GF_LOG_LEVEL=info
        - GF_LOG_CONSOLE_LEVEL=info
        - GF_USERS_ALLOW_SIGN_UP=false
        - GF_USERS_ALLOW_ORG_CREATE=false
```
